{
    'name': '金凌电子 样品中心模块',
    'author': 'Tuna团队',
    'category': 'jinling_erp',
    'description':'用于金凌样品管理',
    'version': '16.0',
    'license': 'LGPL-3',
    'depends': ['mail','jinling_goods'],
    'data': [
        'security/jinling_sample_group.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/jl_sample_apply_view.xml',
        'views/jl_sample_order_view.xml',
        'views/jl_sample_picking_view.xml',
        'views/jl_sample_in_view.xml',
        'menu/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}