{
    'name': '金凌电子 采购模块',
    'author': 'Tuna团队',
    'category': 'jinling_erp',
    'description':'用于金凌电子采购管理',
    'version': '16.0',
    'license': 'LGPL-3',
    'depends': ['mail','web','jinling_warehouse','jinling_goods',],
    'data': [
        'security/jinling_buy_group.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/print_report.xml',
        'views/supplier_view.xml',
        'views/jl_buy_apply_view.xml',
        'views/jl_buy_order_view.xml',
        'views/jl_buy_warehousing_view.xml',
        'views/jl_buy_payment_apply_view.xml',
        'views/jl_buy_price_strategy_view.xml',
        'report/paperformat.xml',
        'report/report_buy_order_template.xml',
        'report/jl_buy_order_report_view.xml',
        'report/jl_buy_order_report_search_view.xml',
        'wizards/jl_buy_order_wizard_view.xml',
        'menu/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'jinling_buy/static/src/js/list_color.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
