{
    'name': '金凌电子 采购模块',
    'author': 'Tuna团队',
    'category': 'jinling_erp',
    'description':'用于金凌电子采购管理',
    'version': '16.0',
    'depends': ['mail','jinling_warehouse','jinling_goods',],
    'data': [
        'security/jinling_buy_group.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/print_report.xml',
        'views/supplier_view.xml',
        'views/jl_buy_apply_view.xml',
        'views/jl_buy_order_view.xml',
        'views/jl_buy_warehousing_view.xml',
        'views/jl_buy_payment_apply_view.xml',
        'report/paperformat.xml',
        'report/report_buy_order_template.xml',
        'menu/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
